### ISSUE TITLE
Multiple uses requires `namespace`/`env` parameters be set and be set to unique values, but this isn't clear.

### ISSUE THREAD

**Issue by jim80net** [scribd/terraform-aws-datadog#13]
## Actual Behavior

When invoking this module more than once (possibly by defining distinct cloudwatch log groups to forward), the module should generate unique lambda function names to avoid collision of the lambda function resource. 

The unique names must be generated from outside the module by supplying unique `namespace`/`env` combinations. The `namespace` and `env` parameters are used to generate the local [`stack_prefix`](https://github.com/scribd/terraform-aws-datadog/blob/b5201c0239419fd9b24576d99b255b8cfc814b29/locals.tf#L2).

The documentation isn't clear about this. 

If possible, it would be ideal to make this simpler, perhaps by generating the lambda function name some other way. 

## Expected Behavior

Clear documentation, or, no need to worry about supplying unique namespace/env combinations. 

## Steps to Reproduce the Problem

1. use the module once to initialize an aws account.
2. use the module again to add cloudwatch log groups, using the same namespace/env combination

**Comment by houqp** [comment]
I am leaning towards documenting on making unique namespace/env combos because stack_prefix is not only used for lambda function right now and more resources could be using it going forward. Is there a use-case where multiple invocations of this module need to use the same namespace/env combo?
