### ISSUE TITLE
ReservedConcurrency setting for forwarder lambda

### ISSUE THREAD

**Issue by desertfoxmb** [scribd/terraform-aws-datadog#39]
When deploying the stack I'm running into an issue where the 100 value for ReservedConcurrency defined in the [yaml template](https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/3.27.0.yaml) for the stack is causing a terraform deployment failure as it is failing the minimum value for unreserved concurrency for all functions.

In our case, we have a significant number of lambdas in the same account. In order to successfully forward logs for them, we have to create multiple log forwarder stacks (no problem there). We decided to break them up by microservice for the time being. That leaves us with around 10 log forwarder stacks. Given that the ReservedConcurrency default is 100, those 10 log forwarders quickly burn through the ReservedConcurrency in an account.

I'll submit a PR for an update that would expose a new variable to allow overriding that value while maintaining the 100 default. If this isn't the desired path forward, how have others gotten around this if they have run into it?

**Comment by desertfoxmb** [comment]
Hmm. Actually, not as easy as I'd hoped since the YAML template is always including the underlying property rather than optionally including it if a value is provided.

**Comment by houqp** [comment]
this approach seems reasonable assuming you can get it to work :)

**Comment by desertfoxmb** [comment]
Unfortunately, the only way to do it was to decouple from the direct link to the Datadog YAML file. So what we ended up doing, for the time being, is forking this repo, downloading the Datadog YAML file, removing ReservedConcurrency parameters/settings from both, and using that way.

Upside, we don't run out of reserved concurrency from log forwarders. The downside, as Datadog or this stack mature we'll have to manually update it as we don't use GitHub internally.

**Comment by houqp** [comment]
@desertfoxmb have you considered contributing an upstream change to datadog YAML file to make it more extensible around configuring ReservedConcurrency?

**Comment by desertfoxmb** [comment]
I have considered it and may do so followed by a PR here. First I had to get our immediate needs taken care of for a year-end objective.

**Comment by houqp** [comment]
yeah, for sure :) Just mentioning it as a solution to reduce maintenance burden for you in the long run.
