### ISSUE TITLE
Allow using Datadog provider 3.x

### ISSUE THREAD

**Issue by breakeverything** [scribd/terraform-aws-datadog#45]
Currently, version.tf does not allow using Datadog provider 3.x versions:
```
  required_providers {
    datadog = {
      source  = "DataDog/datadog"
      version = ">= 2.10, < 3"
    }
  }
```
This is unfortunate, because it forces everything else in the same deployment to use 2.x version of the provider as well and all the new features come only to 3.x. To me it looks like there is no reason to hold back the version in here, but I might have missed something. 

Would it be possible to relax the requirement to allow 3.x versions?

**Comment by houqp** [comment]
I think so as long as there is no major breaking changes from the 3.x version. Please feel free to send a PR
